### PR TITLE
Expose the invoice transaction via filter before the invoice is created.

### PR DESCRIPTION
**Pull request by h4r1m4u**
This patch adds a filter to expose the invoice transaction just before the invoice is created and sent to Quaderno. 

This makes it possible for developers to hook into the filter and change the transaction details if necessary.

### CODE REVIEW

**Comment by polimorfico** [comment]
Thanks for the PR! Why do you want to add a filter instead of using the action? Do you think we should replace the action with the filter?

**Comment by h4r1m4u** [comment]
My pleasure!

I think both the filter and the action hooks have a purpose. The action hooks are useful if you need to trigger something else in the codebase - for example, I could hook into the action and send an email to the site admin to notify them that a new invoice has been sent to Quaderno. 

The filter, on the other hand, lets developers modify the invoice before it's sent to Quaderno. Using the filter, I could add a new note to the invoice, etc. That's not really possible with the action hook as the action hook doesn't return the modified invoice object back to the `edd_quaderno_create_invoice()` function.  

So I think it's good to have both. It provides more flexibility. 

As you'll see from my other PR, my initial need for the filter was to fix buggy behavior when the EDD Discounts Pro extension is used and that's not possible with the action. The filter would allow me to do that, hence the PR. But then I figured it'd be useful to fix the buddy EDD Discounts Pro behavior directly in the core, so that other folks can benefit from it too. Hence the other PR :)

**Comment by polimorfico** [comment]
Thanks for your help! I liked the idea and extended your solution to the credit creation function.

Just merged your PR and deployed the [new version 1.27.1](https://wordpress.org/plugins/edd-quaderno/)

**Comment by h4r1m4u** [comment]
Awesome, thank you very much!

**Pull request merged**
